### ISSUE TITLE
iOS In-App messages never get dismissed

### ISSUE THREAD

**Issue by 4l3ss** [urbanairship/react-native-module#612] opened 2024-12-02 14:06 UTC
# Preliminary Info

### What Airship dependencies are you using?
`@ua/react-native-airship 20.0.4`

### What are the versions of any relevant development tools you are using?
`react-native 0.74.6`

# Report

### What unexpected behavior are you seeing?
There seems to be two issues related to inapp messages dismissal on iOS :
- Messages never automatically dismisses after being displayed, contrary to the default of 15 seconds.
- If the message is only one line long, the banner seems to be less than 100px, and can't be manually swiped

And after some digging, it looks like the 100px limit comes from this https://github.com/urbanairship/ios-library/blob/86f441d5f37b33b3547f6a0b4219bad0efa34d0c/Airship/AirshipAutomation/Source/InAppMessage/View/InAppMessageBannerView.swift#L246

Which means I'm not sure how it could be fixable for shorter messages, while still keeping a reasonable offset limit. 

### What is the expected behavior?
In app messages should automatically disapear after the set timeout, or on user interaction.

### What are the steps to reproduce the unexpected behavior?
- setup an automation on airship back-office including  an in app message in the content
- trigger the automation to display the in-app message
- the message never dismisses, and can't remove it manually if too small

### Do you have logging for the issue?

Not really

**Comment by rlepinski** [comment] 2024-12-02 18:22
Looking at this now.

We will probably have to use a percentage of the height of the modal instead of a min swipe distance. Not sure about the timeout yet but it should be easy to reproduce and fix.

**Comment by rlepinski** [comment] 2024-12-02 20:01
Updating it to use `min(100, bannerHeight * 0.5)` as the min swipe distance

**Comment by rlepinski** [comment] 2024-12-04 16:09
Quick update: We have a release being prepared, its going through QA right now. Assuming they don't find anything we will do a native SDK release. It then takes a few hours to get React Native updated due to pod cdn cache times (once for native SDK, once for our proxy lib). Hopefully will go out tomorrow!

**Comment by rlepinski** [comment] 2024-12-05 18:56
@4l3ss My bad, thats from other changes in this release. Thanks for looking, hoping to get started on the releases soon

**Comment by rlepinski** [comment] 2024-12-06 04:16
Fixed in 20.1.0

**Closed as completed by rlepinski** 2024-12-06 04:16 UTC
