### ISSUE TITLE
Can't manually add into iOS

### ISSUE THREAD

**Issue by Knight704** [urbanairship/react-native-module#127] opened 2018-07-02 14:09 UTC
# Preliminary Info

### What Urban Airship dependencies are you using?
AirshipKit 9.3.0
urbanairship-react-native 1.6.2

### What are the versions of any relevant development tools you are using?
XCode 9.1

# Report

### What unexpected behavior are you seeing?
Runtime error 'Urban Airship Implementation Error🚨 - AirshipResources.bundle could not be found. If using the static library, you must add this file to your application's Copy Bundle Resources phase, or use the AirshipKit embedded framework'
Followed by
'[error] error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter'
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'CoreData: Cannot load NSManagedObjectModel.  nil is an illegal URL parameter'

### What is the expected behavior?
Manual installation work without crashes

### What are the steps to reproduce the unexpected behavior?
- Followed steps [here (UA react-native-module)](https://github.com/urbanairship/react-native-module#ios-installation)
- Then here [manual iOS lib integration](https://docs.urbanairship.com/platform/ios/#manual).
- After all steps I also had to put `libUAirship.a` into 'Link Binary With Libraries' (unfortunately it didn't compile without it).
- Didn't set AIRSHIP_SEARCH_PATH (don't know how). But it won't compile if didn't find path for Airship right?
- Run app

**Comment by crow** [comment] 2018-07-06 22:24
Since you are building and linking the static library - you are going to need to add the AirshipResources.bundle to your copy bundle resources phase.

**Comment by crow** [comment] 2018-07-06 22:41
Your library search path and header search path need to be pointed at the directories where the static lib (.a) and headers are stored, respectively.

**Comment by Knight704** [comment] 2018-07-10 11:52
@crow can you clarify exact actions please? I don't see any AirshipResources.bundle when trying to add something to 'bundle resource phase'. And when I added AirshipKit dir to library search paths and header search paths (recursively), I'm not seeing any effect.

**Comment by himelnagrana** [comment] 2018-07-19 08:34
@crow, I am facing the same problem after upgrading to react-native v0.56 and urban airship to v1.6.2 (from 1.3.1). I am also not finding the step where you mentioned about _AirshipResources.bundle_ file.  Can  you please elaborate a bit or may be mention that step on the docs.

Thanks.

**Comment by marc-scig** [comment] 2018-07-19 18:14
We don't currently have that step in the docs, as the vast majority of the time people are using our AirshipKit.framework, which already has the resources bundle in it. I'll see if I we can fix that.

When the AirshipKit xcode project builds, it creates six products: AirshipKit.framework (one for iOS and one for tvOS), AirshipResources.bundle, libUAirship.a, AirshipKitTests.xctest, and AirshipResources tvos.bundle.

![staticlib1](https://user-images.githubusercontent.com/545958/42961350-6d5c0528-8b43-11e8-8cb1-2ab9cb66e2a3.jpg)

If you right click AirshipResources and select "show in finder", it should take you to its location on disk, assuming you already build the project.

As crow mentioned above, libUAirship.a needs AirshipResources.bundle in order to function. So In your app target's Build Phases tab, you need to add it in the Copy Bundle Resources phase:

![staticlib2](https://user-images.githubusercontent.com/545958/42961684-51835b7a-8b44-11e8-9d89-46f7a34ae7b5.jpg)

Expanding the Copy Bundle Resources phase should bring up a list of all the resources currently added to the app, with a "+" button at the bottom to add additional resources. Use that to add AirshipResources.bundle. That way when the app runs it will copy the bundle over into the app's main bundle, and those resources will be available to the SDK at runtime.

**Comment by himelnagrana** [comment] 2018-07-20 07:01
Thanks a lot @marc-scig - I guess the problem is not using Pod to install arishipkit. Thanks for pointing out. it's fixed now.

**Closed** 2018-07-24 00:03 UTC
