### ISSUE TITLE
InboxMessage extras are always empty

### ISSUE THREAD

**Issue by JorenVos** [urbanairship/react-native-module#403] opened 2022-02-16 10:35 UTC
When sending an inbox message with push notifications, the filled in custom keys are not available in the extras field. (https://docs.airship.com/guides/messaging/user-guide/messages/optional-features/#mc-custom-keys)

How to get data in those extras-field of the `InboxMessage`-type? 

# Preliminary Info

### What Airship dependencies are you using?
"urbanairship-react-native": "^13.2.1"
"react-native": "0.64.2"

**Comment by rlepinski** [comment] 2022-02-16 18:24
It looks like they should be there but I will manually verify. How are you sending the extras? There are two different levels of extras, message center message extras and extras on the push body. Only the one that are set on the message center message should be available.

**Comment by rlepinski** [comment] 2022-02-24 18:46
@JorenVos I was not able to reproduce the issue, could you give me steps that you are using to reproduce?

**Comment by JorenVos** [comment] 2022-03-08 15:01
> @JorenVos I was not able to reproduce the issue, could you give me steps that you are using to reproduce?

In Airship console, I've created a new message. In the "Delivery"-tab, under "Custom keys", I've added a custom key/value pair. This custom key/value does not show up when looking into the messages using `UrbanAirship.getInboxMessages()`. The `extras`-property is always an empty object.

**Comment by rlepinski** [comment] 2022-03-08 16:10
There are two levels of extras. Extras on the push body and extras on the message center message.

You want this one:
<img width="1030" alt="Screen Shot 2022-03-08 at 8 09 16 AM" src="https://user-images.githubusercontent.com/3967591/157277785-319d3f32-ff76-4d51-a615-2eee24c16372.png">

Not this one:
<img width="1037" alt="Screen Shot 2022-03-08 at 8 09 24 AM" src="https://user-images.githubusercontent.com/3967591/157277798-f0c877e9-8960-4317-b7e4-3101a984f4a8.png">

**Comment by rlepinski** [comment] 2022-04-13 19:24
Closing for now, let me know if you are still having issues.

**Closed by rlepinski** 2022-04-13 19:24 UTC
