### ISSUE TITLE
Git folder is in react-native-urbanairship npm package 

### ISSUE THREAD

**Issue by estebanbi** [urbanairship/react-native-module#193] opened 2019-07-15 15:12 UTC
# Preliminary Info

### What Airship dependencies are you using?

react-native-urbanairshi version 3.1.0
### What are the versions of any relevant development tools you are using?

npm 6.8.0
# Report

### What unexpected behavior are you seeing?

Not having .git folder in npm packager
### What are the steps to reproduce the unexpected behavior?

running npm install after installing react-native-urbanairship 
### Do you have logging for the issue?

 npm ERR! pathnode_modules/urbanairship-react-native
npm ERR! code EISGIT
npm ERR! git node_modules/urbanairship-react-native: Appears to be a git repo or submodule.
npm ERR! git  node_modules/urbanairship-react-native
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!    .npm/_logs/2019-07-15T15_09_02_433Z-debug.log

**Comment by rlepinski** [comment] 2019-07-15 18:48
We will look into today. Thanks for the report.

**Comment by rlepinski** [comment] 2019-07-15 20:30
Normally .git directory is automatically excluded from packaging, but there seems to be a bug https://npm.community/t/npm-pack-includes-items-from-git-folder-if-there-is-a-branch-called-readme-regression-in-6-9-0/6044

That bug is about a branch named `readme`, but it appears to be happening for us for branch named `changelog`.

**Comment by rlepinski** [comment] 2019-07-15 20:33
Looks like a bug in npm 6.9 that was used to publish the package. A new package will be up shortly.

**Comment by rlepinski** [comment] 2019-07-15 23:21
Fixed in 3.1.1

**Closed by rlepinski** 2019-07-15 23:21 UTC
