### ISSUE TITLE
Installing airship breaks share extension

### ISSUE THREAD

**Issue by raquelmsmith** [urbanairship/react-native-module#378] opened 2021-12-09 05:05 UTC
# Preliminary Info

### What Airship dependencies are you using?

"urbanairship-react-native": "^13.0.2",
"react-native": "0.64.1",

### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?

After installing Airship, my share extension no longer works on iOS. I am using https://github.com/meedan/react-native-share-menu for the share extension. 

### What is the expected behavior?

I'd expect that the share sheet would continue working.

### What are the steps to reproduce the unexpected behavior?

Init new RN project.
Set up a share sheet as described in https://github.com/meedan/react-native-share-menu.
Install airship for RN as described in this repo.
See that the share sheet no longer launches when clicked.

### Do you have logging for the issue?

See comment https://github.com/urbanairship/react-native-module/issues/378#issuecomment-990064779 for errors.

**Comment by raquelmsmith** [comment] 2021-12-09 17:29
I opened up flipper and saw errors there!
```
[E] AirshipKit/Airship.swift takeOff(_:launchOptions:) [Line 184] 🚨Airship Implementation Error🚨: AirshipConfig.plist file is missing. Unable to takeOff.
```

If I enable the AirshipConfig.plist for the BrunchShare target, I then get:

```
[E] AirshipKit/Config.swift validate() [Line 486] 🚨Airship Implementation Error🚨: The airship config options is missing URL allow list rules for SCOPE_OPEN. By default only Airship, YouTube, mailto, sms, and tel URLs will be allowed. To suppress this error, specify allow list rules by providing rules for URLAllowListScopeOpenURL or URLAllowList. Alternatively you can suppress this error and keep the default rules by using the flag suppressAllowListError. For more information, see https://docs.airship.com/platform/ios/getting-started/#url-allow-list.
```

I don't want/need Airship running in this target. How do I remove it from this target?

**Comment by rlepinski** [comment] 2021-12-10 03:06
Could you provide your pod file?

**Comment by raquelmsmith** [comment] 2021-12-10 04:12
I ended up trying this with OneSignal to see if it was Airship related or the share extension. With OneSignal it wouldn't work either. So, I ended up removing the share package I was using and implementing a basic one from scratch, which isn't having any issues with Airship.

**Comment by rlepinski** [comment] 2021-12-10 16:49
I believe https://github.com/meedan/react-native-share-menu/blob/master/SHARE_EXTENSION_VIEW.md#bundle-js-code-and-assets-in-your-share-extension might be the reason why its causing issues. You will probably have to modify the target to exclude any automatic linked packages from react-native. I can try to help reproduce next week if you are still needing it, but it sounds like you have a workaround.

Going to close the issue, let me know if you need more help.

**Closed by rlepinski** 2021-12-10 16:49 UTC

**Comment by raquelmsmith** [comment] 2021-12-10 18:19
Man if you could help me get the share extension working again that would be amazing. The one I implemented from scratch kinda works but has bugs and I'd much rather use the package. I know it's not your code to maintain but if you are willing to help that would be, like, the most amazing thing ever 😅

**Comment by rlepinski** [comment] 2021-12-14 06:50
Could you share your pod file? Ill see if I have a similar issue

**Comment by raquelmsmith** [comment] 2021-12-14 16:49
Yep! 

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'Brunch' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'AirshipServiceExtension' do
    pod 'AirshipExtensions/NotificationService'
  end

  target 'BrunchTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.91.1', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4' })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
    flipper_post_install(installer)
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
```

**Comment by rlepinski** [comment] 2021-12-19 05:54
@raquelmsmith Could you try my branch `GH-378` to see if it resolves your issue. I am having troubles getting the share menu to work properly, but I was able to reproduce and workaround the crash. Let me know if that works for you

**Comment by raquelmsmith** [comment] 2021-12-19 17:03
Thank you!! When I try to install it with 

```
"urbanairship-react-native": "github:urbanairship/react-native-module#pull/384/head",
```

I get an error: `error Can't add "urbanairship-react-native": invalid package version undefined.`

Any suggestions?

**Comment by rlepinski** [comment] 2022-01-04 16:21
sorry @raquelmsmith  I was on holiday break. I merged the change into main if you want test. I believe we should have a patch release out this week if you want to wait. That ref looks odd to me, you probably need to point to the branch and not the PR.

**Comment by raquelmsmith** [comment] 2022-01-07 21:43
Thank you @rlepinski! I will give it another go early next week.

**Comment by raquelmsmith** [comment] 2022-01-13 16:17
Sorry for the delay with this, but your fix seems to have worked!! Thank you so much!! I have another question that I will put in another issue. Thank you again!!
